import type { Publication, ImportantDate } from './types'

export const MONTHS = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
]

export const DAYS_OF_WEEK = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado']

export const IMPORTANT_DATES: ImportantDate[] = [
  // Enero
  { id: '1', date: '24/01', title: 'Día Internacional de la Educación (UNESCO)', month: 1 },
  // Febrero
  { id: '2', date: '03/02', title: 'Día Internacional del Abogado', month: 2 },
  { id: '3', date: '04/02', title: 'Día Mundial contra el Cáncer', month: 2 },
  { id: '4', date: '09/02', title: 'Día del Periodista en Colombia', month: 2 },
  { id: '5', date: '13/02', title: 'Día Mundial de la Radio', month: 2 },
  { id: '6', date: '14/02', title: 'Día de San Valentín', month: 2 },
  { id: '7', date: '20/02', title: 'Día del Camarógrafo y Fotógrafo', month: 2 },
  // Marzo
  { id: '8', date: '01/03', title: 'Día del Contador Público', month: 3 },
  { id: '9', date: '03/03', title: 'Día Mundial de la Vida Silvestre (UNESCO)', month: 3 },
  { id: '10', date: '08/03', title: 'Día Internacional de la Mujer', month: 3 },
  { id: '11', date: '14/03', title: 'Día Nacional del Trabajador de la Construcción', month: 3 },
  { id: '12', date: '17/03', title: 'Día del Psicoorientador', month: 3 },
  { id: '13', date: '19/03', title: 'Día del Hombre en Colombia', month: 3 },
  { id: '14', date: '20/03', title: 'Día Internacional de la eliminación de la discriminación racial', month: 3 },
  { id: '15', date: '21/03', title: 'Día Mundial del Síndrome de Down', month: 3 },
  { id: '16', date: '21/03', title: 'Día Mundial del Agua (UNESCO)', month: 3 },
  { id: '17', date: '23/03', title: 'Día del Optómetra', month: 3 },
  { id: '18', date: '30/03', title: 'Día Internacional de las Trabajadoras del Hogar', month: 3 },
  // Abril
  { id: '19', date: '07/04', title: 'Día Mundial de la Salud', month: 4 },
  { id: '20', date: '09/04', title: 'Día de la Memoria y Solidaridad con las Víctimas del Conflicto Armado', month: 4 },
  { id: '21', date: '16/04', title: 'Día Mundial del Emprendimiento', month: 4 },
  { id: '22', date: '22/04', title: 'Día Internacional de la Madre Tierra (UNESCO)', month: 4 },
  { id: '23', date: '23/04', title: 'Día del Idioma', month: 4 },
  { id: '24', date: '25/04', title: 'Día del Niño en Colombia', month: 4 },
  { id: '25', date: '25/04', title: 'Día del Bacteriólogo', month: 4 },
  { id: '26', date: '26/04', title: 'Día de la Secretaria en Colombia', month: 4 },
  { id: '27', date: '27/04', title: 'Día del Diseñador Gráfico', month: 4 },
  { id: '28', date: '28/04', title: 'Día Mundial de la Seguridad y la Salud en el Trabajo', month: 4 },
  // Mayo
  { id: '29', date: '01/05', title: 'Día del Trabajo', month: 5 },
  { id: '30', date: '02/05', title: 'Día Mundial contra el Bullying o el Acoso Escolar', month: 5 },
  { id: '31', date: '03/05', title: 'Día Mundial de la Libertad de Prensa / Día del Periodista', month: 5 },
  { id: '32', date: '04/05', title: 'Día Internacional del Bombero', month: 5 },
  { id: '33', date: '07/05', title: 'Día Mundial de la Salud Mental Materna', month: 5 },
  { id: '34', date: '10/05', title: 'Día de la Madre en Colombia', month: 5 },
  { id: '35', date: '12/05', title: 'Día Internacional de la Enfermería / Día del Estadista', month: 5 },
  { id: '36', date: '15/05', title: 'Día del Maestro en Colombia', month: 5 },
  { id: '37', date: '17/05', title: 'Día Mundial contra la Homofobia, Transfobia y Bifobia', month: 5 },
  { id: '38', date: '20/05', title: 'Día del Psicólogo', month: 5 },
  { id: '39', date: '21/05', title: 'Día Mundial de la Diversidad Cultural / Día de la Afrocolombianidad', month: 5 },
  { id: '40', date: '23/05', title: 'Día del Estudiante', month: 5 },
  // Junio
  { id: '41', date: '01/06', title: 'Día del Campesino', month: 6 },
  { id: '42', date: '05/06', title: 'Día Mundial del Medio Ambiente (UNESCO)', month: 6 },
  { id: '43', date: '12/06', title: 'Día Mundial contra el Trabajo Infantil', month: 6 },
  { id: '44', date: '21/06', title: 'Día del Padre', month: 6 },
  { id: '45', date: '22/06', title: 'Día del Abogado en Colombia', month: 6 },
  // Julio
  { id: '46', date: '04/07', title: 'Día del Cooperativismo', month: 7 },
  { id: '47', date: '20/07', title: 'Día de la Independencia de Colombia', month: 7 },
  // Agosto
  { id: '48', date: '07/08', title: 'Batalla de Boyacá', month: 8 },
  { id: '49', date: '12/08', title: 'Día Internacional de la Juventud', month: 8 },
  // Septiembre
  { id: '50', date: '21/09', title: 'Día Internacional de la Paz', month: 9 },
  // Octubre
  { id: '51', date: '12/10', title: 'Día de la Raza', month: 10 },
  { id: '52', date: '31/10', title: 'Halloween', month: 10 },
  // Noviembre
  { id: '53', date: '01/11', title: 'Día de Todos los Santos', month: 11 },
  { id: '54', date: '11/11', title: 'Independencia de Cartagena', month: 11 },
  // Diciembre
  { id: '55', date: '07/12', title: 'Día de las Velitas', month: 12 },
  { id: '56', date: '25/12', title: 'Navidad', month: 12 },
]

// Helper to get today's date as YYYY-MM-DD
function getTodayStr() {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

const DAYS = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado']
function getTodayDay() { return DAYS[new Date().getDay()] }

export const SAMPLE_PUBLICATIONS: Publication[] = [
  // Publicaciones de hoy (dinamicas)
  {
    id: 'today-1',
    date: getTodayStr(),
    dayOfWeek: getTodayDay(),
    theme: 'NOTICIAS SUPER',
    description: 'COMUNICADO OFICIAL DE LA SUPERSUBSIDIO',
    objective: 'informar',
    networks: ['instagram', 'facebook', 'twitter', 'linkedin'],
    time: '9:00 AM',
    hashtags: ['#Supersubsidio', '#SupervisarEsCuidar'],
    caption: 'Conoce las ultimas novedades de la Superintendencia del Subsidio Familiar.',
    format: 'imagen',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO'],
    observations: '',
    status: 'programado',
    links: [],
  },
  {
    id: 'today-2',
    date: getTodayStr(),
    dayOfWeek: getTodayDay(),
    theme: 'APRENDE CON LA SUPER',
    description: 'TIPS PARA ACCEDER AL SUBSIDIO DE VIVIENDA',
    objective: 'educar',
    networks: ['instagram', 'facebook', 'tiktok'],
    time: '2:00 PM',
    hashtags: ['#SubsidioDeVivienda', '#Supersubsidio', '#SupervisarEsCuidar'],
    caption: 'Te compartimos las claves para acceder al subsidio de vivienda a traves de tu caja de compensacion.',
    format: 'video',
    responsibles: ['JAVIER DIAZ', 'JENNIFER QUINTERO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
  {
    id: '1',
    date: '2026-03-01',
    dayOfWeek: 'Domingo',
    theme: 'APRENDE CON LA SUPER',
    description: 'VALOR CUOTA MONETARIA 2026',
    objective: 'educar',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '10:00 AM',
    hashtags: ['#SubsidioFamiliar', '#CuotaMonetaria', '#Supersubsidio', '#SupervisarEsCuidar'],
    caption: '¡Atención trabajadores y trabajadoras de Colombia! Ya están definidas las nuevas cuotas monetarias del subsidio familiar para 2026. Consulta los valores correspondientes a tu departamento y acércate a tu Caja de Compensación Familiar para conocer cómo acceder a este beneficio.',
    format: 'video',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO'],
    observations: '',
    status: 'publicado',
    links: [
      { network: 'instagram', url: 'https://www.instagram.com/p/DUiOE2LyDrQs/' },
      { network: 'tiktok', url: 'https://www.tiktok.com/@supersubsidio/video/7501916286141361416' },
      { network: 'twitter', url: 'https://x.com/Supersubsidio/status/2018037103385330170' },
      { network: 'linkedin', url: 'https://www.linkedin.com/feed/update/urn:li:activity:7423744402981176233' },
    ],
  },
  {
    id: '2',
    date: '2026-03-02',
    dayOfWeek: 'Lunes',
    theme: 'APRENDE CON LA SUPER',
    description: 'PIEZA GRÁFICA ACERCA DE PERSONAS QUE GENERAN DERECHO A CUOTA MONETARIA',
    objective: 'educar',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '11:00 AM',
    hashtags: ['#SubsidioFamiliar', '#CuotaMonetaria', '#Supersubsidio', '#SupervisarEsCuidar'],
    caption: '',
    format: 'imagen',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO', 'JENNIFER QUINTERO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
  {
    id: '3',
    date: '2026-03-03',
    dayOfWeek: 'Martes',
    theme: 'APRENDE CON LA SUPER',
    description: 'TODO LO QUE DEBES SABER ACERCA DEL SUBSIDIO FAMILIAR',
    objective: 'educar',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '10:00 AM',
    hashtags: ['#SubsidioFamiliar', '#CuotaMonetaria', '#SupervisarEsCuidar'],
    caption: '',
    format: 'video',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
  {
    id: '4',
    date: '2026-03-04',
    dayOfWeek: 'Miércoles',
    theme: 'APRENDE CON LA SUPER',
    description: 'CARRUSEL SOBRE CANALES DE ATENCIÓN DE LA SUPERSUBSIDIO',
    objective: 'branding',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '3:00 PM',
    hashtags: ['#Supersubsidio', '#SupervisarEsCuidar'],
    caption: '',
    format: 'carrusel',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO', 'OLGA CARANTONIO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
  {
    id: '5',
    date: '2026-03-05',
    dayOfWeek: 'Jueves',
    theme: 'APRENDE CON LA SUPER',
    description: 'CÓMO SE CALCULA EL VALOR DE LA CUOTA MONETARIA',
    objective: 'educar',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '11:00 AM',
    hashtags: ['#SubsidioFamiliar', '#CuotaMonetaria', '#Supersubsidio', '#SupervisarEsCuidar'],
    caption: '',
    format: 'video',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
  {
    id: '6',
    date: '2026-03-06',
    dayOfWeek: 'Viernes',
    theme: 'LA SUPER TE RESPONDE',
    description: '¿SE PUEDE APLICAR MÁS DE UNA VEZ AL SUBSIDIO DE VIVIENDA?',
    objective: 'educar',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '3:00 PM',
    hashtags: ['#SubsidioDeVivienda', '#Supersubsidio', '#SupervisarEsCuidar'],
    caption: '',
    format: 'video',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO', 'JENNIFER QUINTERO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
  {
    id: '7',
    date: '2026-03-07',
    dayOfWeek: 'Sábado',
    theme: 'RESUMEN: ASÍ VA LA SUPER',
    description: 'LO MÁS DESTACADO DE LA SEMANA',
    objective: 'branding',
    networks: ['instagram', 'facebook', 'tiktok', 'twitter', 'linkedin'],
    time: '3:00 PM',
    hashtags: ['#Supersubsidio', '#SupervisarEsCuidar'],
    caption: '',
    format: 'video',
    responsibles: ['JAVIER DIAZ', 'ISABELLA CARO'],
    observations: '',
    status: 'pendiente',
    links: [],
  },
]
